### ISSUE TITLE
Unable to use other Sim800L Libraries after using this Library

### ISSUE THREAD

**Issue by oOKunalOo** [shuvangkar/SIM800L#1]
Hi, First of all sorry for using such mean title. Getting right to the point, I am unable to use any other library for Sim800l apart from this. Other libraries worked before using this library. Now, for some reason only this library works, while others don't.

**Comment by shuvangkardas** [comment]
I developed the library to operate on higher baud rate. So my library is changing baud rate of your SIM module. This might be one the reasons, others libraries are not working.
